In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [3]:
dataset = pd.read_csv('/content/sample_data/diabetes.csv')

In [4]:
dataset.head(2)

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0

[2 rows x 9 columns]

In [6]:
#number of rows and columns
dataset.shape

(768, 9)

#statistical Measures

In [7]:
dataset.describe()

Pregnancies     Glucose  ...         Age     Outcome
count   768.000000  768.000000  ...  768.000000  768.000000
mean      3.845052  120.894531  ...   33.240885    0.348958
std       3.369578   31.972618  ...   11.760232    0.476951
min       0.000000    0.000000  ...   21.000000    0.000000
25%       1.000000   99.000000  ...   24.000000    0.000000
50%       3.000000  117.000000  ...   29.000000    0.000000
75%       6.000000  140.250000  ...   41.000000    1.000000
max      17.000000  199.000000  ...   81.000000    1.000000

[8 rows x 9 columns]

In [11]:
dataset.Outcome.value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [12]:
dataset.groupby('Outcome').mean()

Pregnancies     Glucose  ...  DiabetesPedigreeFunction        Age
Outcome                           ...                                     
0           3.298000  109.980000  ...                  0.429734  31.190000
1           4.865672  141.257463  ...                  0.550500  37.067164

[2 rows x 8 columns]

In [13]:
target = dataset['Outcome']


In [15]:
dataset = dataset.drop(columns='Outcome', axis=1)

In [17]:
scalar = StandardScaler()

dataset_s = scalar.fit(dataset)

In [18]:
stan_dataset = dataset_s.transform(dataset)
stan_dataset

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [19]:
X = stan_dataset
Y = target

In [30]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, stratify=Y, random_state=2)
print(X_train.shape, Y_train.shape)

(614, 8) (614,)


#MODEL TRAINING

In [31]:
classifier = svm.SVC(kernel='linear')

In [32]:
classifier.fit(X_train, Y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

#model EVal

In [33]:
X_train_prediction = classifier.predict(X_train)
training_accuracy = accuracy_score(Y_train, X_train_prediction)

In [34]:
training_accuracy

0.7866449511400652

In [35]:
X_test_prediction = classifier.predict(X_test)
testing_accuracy = accuracy_score(Y_test, X_test_prediction)

In [36]:
testing_accuracy

0.7727272727272727

Making a Predicting System

In [47]:
input_data = (5,166,72,19,175,25.8,0.587,51)

input_data_as_np_array = np.asarray(input_data)

In [48]:
input_data_as_np_array

array([  5.   , 166.   ,  72.   ,  19.   , 175.   ,  25.8  ,   0.587,
        51.   ])

In [49]:
inp_reshape = input_data_as_np_array.reshape(1,-1)

In [50]:
inp_reshape.shape

(1, 8)

In [51]:
test_standardize = scalar.transform(inp_reshape)

In [52]:
pred = classifier.predict(test_standardize)

In [53]:
pred

array([1])